airflow:
  ingress:
    enabled: false
  executor: LocalExecutor
  webserver:
    service:
      type: ClusterIP

  migrateDatabaseJob:
    enabled: true

  waitForMigrations:
    enabled: true
    timeout: 300