argo-cd:
  crds:
    install: true
    keep: false
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd-umer.786999.xyz
        external-dns.alpha.kubernetes.io/target: 192.99.176.115
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hostname: argocd-umer.786999.xyz
      tls: true
